# 1) /api と /api/* を Heroku STG へリライト
[[redirects]]
  from = "/api"
  to   = "https://monolisk-stg-192515f15c7f.herokuapp.com/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to   = "https://monolisk-stg-192515f15c7f.herokuapp.com/api/:splat"
  status = 200
  force = true

# 2) SPA のフォールバックは最後に
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200