services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: monolisk
      POSTGRES_USER: monolisk
      POSTGRES_PASSWORD: monolisk
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1125:1025"

volumes:
  db_data: